//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordDocumentBuilder {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Договоры\\")]
        public string ContractsFolderPath {
            get {
                return ((string)(this["ContractsFolderPath"]));
            }
            set {
                this["ContractsFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Кандидаты\\Кандидаты.xlsx")]
        public string Candidates_FilePath {
            get {
                return ((string)(this["Candidates_FilePath"]));
            }
            set {
                this["Candidates_FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Кандидаты\\КАНДИДАТЫ ЗС РО форма_БПЛ ТВ.dotx")]
        public string Candidates_TemplateFilePath_ТВ {
            get {
                return ((string)(this["Candidates_TemplateFilePath_ТВ"]));
            }
            set {
                this["Candidates_TemplateFilePath_ТВ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Кандидаты\\КАНДИДАТЫ ЗС РО форма_БПЛ РВ.dotx")]
        public string Candidates_TemplateFilePath_РВ {
            get {
                return ((string)(this["Candidates_TemplateFilePath_РВ"]));
            }
            set {
                this["Candidates_TemplateFilePath_РВ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Кандидаты\\Талоны.xlsm")]
        public string Candidates_TalonsFilePath {
            get {
                return ((string)(this["Candidates_TalonsFilePath"]));
            }
            set {
                this["Candidates_TalonsFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Кандидаты\\Талоны для формирования\\Талоны Маяк.xlsx")]
        public string Candidates_TalonsFilePath_Маяк {
            get {
                return ((string)(this["Candidates_TalonsFilePath_Маяк"]));
            }
            set {
                this["Candidates_TalonsFilePath_Маяк"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Кандидаты\\Талоны для формирования\\Талоны Радио России.xlsx")]
        public string Candidates_TalonsFilePath_Радио_России {
            get {
                return ((string)(this["Candidates_TalonsFilePath_Радио_России"]));
            }
            set {
                this["Candidates_TalonsFilePath_Радио_России"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Кандидаты\\Талоны для формирования\\Талоны Вести ФМ.xlsx")]
        public string Candidates_TalonsFilePath_Вести_ФМ {
            get {
                return ((string)(this["Candidates_TalonsFilePath_Вести_ФМ"]));
            }
            set {
                this["Candidates_TalonsFilePath_Вести_ФМ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Кандидаты\\Талоны для формирования\\Талоны Россия 1.xlsx")]
        public string Candidates_TalonsFilePath_Россия_1 {
            get {
                return ((string)(this["Candidates_TalonsFilePath_Россия_1"]));
            }
            set {
                this["Candidates_TalonsFilePath_Россия_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Кандидаты\\Талоны для формирования\\Талоны Россия 24.xlsx")]
        public string Candidates_TalonsFilePath_Россия_24 {
            get {
                return ((string)(this["Candidates_TalonsFilePath_Россия_24"]));
            }
            set {
                this["Candidates_TalonsFilePath_Россия_24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Партии\\Партии.xlsx")]
        public string Parties_FilePath {
            get {
                return ((string)(this["Parties_FilePath"]));
            }
            set {
                this["Parties_FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Партии\\ПАРТИИ ЗС РО_БПЛ ТВ.dotx")]
        public string Parties_TemplateFilePath_ТВ {
            get {
                return ((string)(this["Parties_TemplateFilePath_ТВ"]));
            }
            set {
                this["Parties_TemplateFilePath_ТВ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Партии\\ПАРТИИ ЗС РО_БПЛ РВ.dotx")]
        public string Parties_TemplateFilePath_РВ {
            get {
                return ((string)(this["Parties_TemplateFilePath_РВ"]));
            }
            set {
                this["Parties_TemplateFilePath_РВ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Партии\\Талоны.xlsm")]
        public string Parties_TalonsFilePath {
            get {
                return ((string)(this["Parties_TalonsFilePath"]));
            }
            set {
                this["Parties_TalonsFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Партии\\Талоны для формирования\\Талоны Маяк.xlsx")]
        public string Parties_TalonsFilePath_Маяк {
            get {
                return ((string)(this["Parties_TalonsFilePath_Маяк"]));
            }
            set {
                this["Parties_TalonsFilePath_Маяк"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Партии\\Талоны для формирования\\Талоны Радио России.xlsx")]
        public string Parties_TalonsFilePath_Радио_России {
            get {
                return ((string)(this["Parties_TalonsFilePath_Радио_России"]));
            }
            set {
                this["Parties_TalonsFilePath_Радио_России"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Партии\\Талоны для формирования\\Талоны Вести ФМ.xlsx")]
        public string Parties_TalonsFilePath_Вести_ФМ {
            get {
                return ((string)(this["Parties_TalonsFilePath_Вести_ФМ"]));
            }
            set {
                this["Parties_TalonsFilePath_Вести_ФМ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Партии\\Талоны для формирования\\Талоны Россия 1.xlsx")]
        public string Parties_TalonsFilePath_Россия_1 {
            get {
                return ((string)(this["Parties_TalonsFilePath_Россия_1"]));
            }
            set {
                this["Parties_TalonsFilePath_Россия_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Партии\\Талоны для формирования\\Талоны Россия 24.xlsx")]
        public string Parties_TalonsFilePath_Россия_24 {
            get {
                return ((string)(this["Parties_TalonsFilePath_Россия_24"]));
            }
            set {
                this["Parties_TalonsFilePath_Россия_24"] = value;
            }
        }
    }
}
