//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordDocumentBuilder {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Договоры\\")]
        public string ContractsFolderPath {
            get {
                return ((string)(this["ContractsFolderPath"]));
            }
            set {
                this["ContractsFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Кандидаты.xlsx")]
        public string CandidatesFilePath {
            get {
                return ((string)(this["CandidatesFilePath"]));
            }
            set {
                this["CandidatesFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Талоны.xlsm")]
        public string TalonsFilePath {
            get {
                return ((string)(this["TalonsFilePath"]));
            }
            set {
                this["TalonsFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Талоны для формирования\\Талоны Маяк.xlsx")]
        public string TalonsFilePath_Маяк {
            get {
                return ((string)(this["TalonsFilePath_Маяк"]));
            }
            set {
                this["TalonsFilePath_Маяк"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Талоны для формирования\\Талоны Радио России.xlsx")]
        public string TalonsFilePath_Радио_России {
            get {
                return ((string)(this["TalonsFilePath_Радио_России"]));
            }
            set {
                this["TalonsFilePath_Радио_России"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Талоны для формирования\\Талоны Вести ФМ.xlsx")]
        public string TalonsFilePath_Вести_ФМ {
            get {
                return ((string)(this["TalonsFilePath_Вести_ФМ"]));
            }
            set {
                this["TalonsFilePath_Вести_ФМ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Талоны для формирования\\Талоны Россия 1.xlsx")]
        public string TalonsFilePath_Россия_1 {
            get {
                return ((string)(this["TalonsFilePath_Россия_1"]));
            }
            set {
                this["TalonsFilePath_Россия_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Талоны для формирования\\Талоны Россия 24.xlsx")]
        public string TalonsFilePath_Россия_24 {
            get {
                return ((string)(this["TalonsFilePath_Россия_24"]));
            }
            set {
                this["TalonsFilePath_Россия_24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\КАНДИДАТЫ ЗС РО форма_БПЛ ТВ.dotx")]
        public string TemplateFilePath_ТВ {
            get {
                return ((string)(this["TemplateFilePath_ТВ"]));
            }
            set {
                this["TemplateFilePath_ТВ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\КАНДИДАТЫ ЗС РО форма_БПЛ РВ.dotx")]
        public string TemplateFilePath_РВ {
            get {
                return ((string)(this["TemplateFilePath_РВ"]));
            }
            set {
                this["TemplateFilePath_РВ"] = value;
            }
        }
    }
}
